app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('school.urls')),
]

app/school/urls.py
from django.urls import path

from . import views

app_name = 'school'
urlpatterns = [
    path('', views.index, name='index'),
    path('school/', views.school_list, name='school-list'),
    path('school/<int:school_id>/', views.school_detail, name='school-detail'),
    path('student/', views.student_list, name='student-list'),
    path('student/<int:student_id>/', views.student_detail, name='student-detail'),
]

app/school/models.py
from django.db import models


class School(models.Model):
    school_name = models.CharField(max_length=200)

    def __str__(self):
        return self.school_name


class Student(models.Model):
    school = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
    )
    student_name = models.CharField(max_length=200)
    friends = models.ManyToManyField(
        'self',
        through='Friend',
        symmetrical=False,
    )

    def __str__(self):
        return self.student_name

class Friend(models.Model):
    school = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
    )
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
    )

app/school/views.py
from django.shortcuts import render

from .models import School, Student


def index(request):
    return render(request, 'index.html')


def school_list(request):
    schools = School.objects.all()
    context = {
        'schools': schools,
    }
    return render(request, 'school_list.html', context)


def school_detail(request, school_id):
    school = School.objects.get(pk=school_id)
    students = school.student_set.all()
    context = {
        'school': school,
        'students': students,
    }
    return render(request, 'school_detail.html', context)


def student_list(request):
    students = Student.objects.all()
    context = {
        'students': students,
    }
    return render(request, 'student_list.html', context)


def student_detail(request, student_id):
    student = Student.objects.get(pk=student_id)
    friends = student.friends.all()
    school = student.school
    context = {
        'student': student,
        'friends': friends,
        'school': school,
    }
    return render(request, 'student_detail.html', context)

app/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
</head>
<body>
<h1>Index</h1>
<h3><a href="{% url 'school:school-list' %}">학교목록</a></h3>
<h3><a href="{% url 'school:student-list' %}">학생목록</a></h3>
</body>
</html>

app/templates/school_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>school_detail</title>
</head>
<body>
<h1>{{ school }}</h1>
<h2>Student List</h2>
{% for student in students %}
<a href="{% url 'school:student-detail' student.pk %}">{{ student.name }}</a><br>
{% endfor %}
</body>
</html>

app/templates/school_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>School List</title>
</head>
<body>
<h1>School List</h1>
{% for school in schools %}
<a href="{% url 'school:school-detail' school.id %}">{{ school }}</a><br>
{% endfor %}
</body>
</html>

app/templates/student_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>student_detail</title>
</head>
<body>
<h1>{{ student.name }}</h1>
<h2>School : {{ school }}</h2>
<h3>Friend List</h3>
{% for friend in friends %}
{{ friend.name }}<br>
{% endfor %}
</body>
</html>

app/templates/student_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>student_list</title>
</head>
<body>
{% for student in students %}
<a href="{% url 'school:student-detail' student.id %}">{{ student }}</a><br>
{% endfor %}
</body>
</html>